## Import library

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/Churn_Modelling.csv')

Analyze Dataset

In [ ]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
df.tail()

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [ ]:
df.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [ ]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

Binary Classification

In [ ]:
#define x and y
x = df.iloc[:,7:13]
y = df.iloc[:,13:]
x.head(),y.head()

(   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
 0       2       0.00              1          1               1   
 1       1   83807.86              1          0               1   
 2       8  159660.80              3          1               0   
 3       1       0.00              2          0               0   
 4       2  125510.82              1          1               1   
 
    EstimatedSalary  
 0        101348.88  
 1        112542.58  
 2        113931.57  
 3         93826.63  
 4         79084.10  ,
    Exited
 0       1
 1       0
 2       1
 3       0
 4       0)

Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ssx = ss.fit_transform(x)
print(ssx[:5])
print(pd.DataFrame(ssx).describe())

[[-1.04175968 -1.22584767 -0.91158349  0.64609167  0.97024255  0.02188649]
 [-1.38753759  0.11735002 -0.91158349 -1.54776799  0.97024255  0.21653375]
 [ 1.03290776  1.33305335  2.52705662  0.64609167 -1.03067011  0.2406869 ]
 [-1.38753759 -1.22584767  0.80773656 -1.54776799 -1.03067011 -0.10891792]
 [-1.04175968  0.7857279  -0.91158349  0.64609167  0.97024255 -0.36527578]]
                  0             1             2             3             4  \
count  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04   
mean  -1.078249e-16 -6.252776e-17  1.634248e-17 -5.258016e-17 -7.389644e-17   
std    1.000050e+00  1.000050e+00  1.000050e+00  1.000050e+00  1.000050e+00   
min   -1.733315e+00 -1.225848e+00 -9.115835e-01 -1.547768e+00 -1.030670e+00   
25%   -6.959818e-01 -1.225848e+00 -9.115835e-01 -1.547768e+00 -1.030670e+00   
50%   -4.425957e-03  3.319639e-01 -9.115835e-01  6.460917e-01  9.702426e-01   
75%    6.871299e-01  8.199205e-01  8.077366e-01  6.460917e-01  9.702426

In [ ]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
mmsx = mms.fit_transform(x)
print(mmsx[:5])
print(pd.DataFrame(mmsx).describe())

[[0.2        0.         0.         1.         1.         0.50673489]
 [0.1        0.33403148 0.         0.         1.         0.56270874]
 [0.8        0.63635718 0.66666667 1.         0.         0.56965435]
 [0.1        0.         0.33333333 0.         0.         0.46912005]
 [0.2        0.50024622 0.         1.         1.         0.39540036]]
                  0             1             2            3             4  \
count  10000.000000  10000.000000  10000.000000  10000.00000  10000.000000   
mean       0.501280      0.304848      0.176733      0.70550      0.515100   
std        0.289217      0.248696      0.193885      0.45584      0.499797   
min        0.000000      0.000000      0.000000      0.00000      0.000000   
25%        0.300000      0.000000      0.000000      0.00000      0.000000   
50%        0.500000      0.387402      0.000000      1.00000      1.000000   
75%        0.700000      0.508749      0.333333      1.00000      1.000000   
max        1.000000      1.000

In [ ]:
from keras.utils import np_utils
npy=np_utils.to_categorical(y)
print(npy[:5])

[[0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]]


In [ ]:
import pandas as pd
ys=y.squeeze()
pdy=pd.get_dummies(ys).values
print(pdy[:5])

[[0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]]


In [ ]:
pdydf=pd.get_dummies(ys)
print(pdydf.head(2))


   0  1
0  0  1
1  1  0


Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split


In [ ]:
x_train,x_test,y_train,y_test=train_test_split(ssx,pdy,test_size=.25,random_state=15)

In [ ]:
y_train.shape

(7500, 2)

Import and Build Neural Network

In [ ]:
print(x_train. shape)
print(y_train. shape)
print(x_test.shape)
print(y_test.shape)

(7500, 6)
(7500, 2)
(2500, 6)
(2500, 2)


In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense,Activation
from keras.optimizers import Adam
from keras.metrics import binary_crossentropy

In [ ]:
#single layer feedforward networks
model=Sequential([
#input layer
Dense(units=5,input_dim=6,activation='relu'),
#hidden
#Dense(units=25,activation='sigmoid'),
#Dense(units=35,activation='sigmoid),
#Dense(units=55,activation='sigmoid'),
#output layers
Dense(units=2,activation='sigmoid')
])

In [ ]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics='accuracy')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 5)                 35        
                                                                 
 dense_1 (Dense)             (None, 2)                 12        
                                                                 
Total params: 47
Trainable params: 47
Non-trainable params: 0
_________________________________________________________________


Train the Model

In [ ]:
d=model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=200)

Epoch 1/200
235/235 [==============================] - 2s 4ms/step - loss: 0.6627 - accuracy: 0.6207 - val_loss: 0.5915 - val_accuracy: 0.7004
Epoch 2/200
235/235 [==============================] - 1s 3ms/step - loss: 0.5536 - accuracy: 0.7567 - val_loss: 0.5339 - val_accuracy: 0.7872
Epoch 3/200
235/235 [==============================] - 1s 3ms/step - loss: 0.5207 - accuracy: 0.7951 - val_loss: 0.5117 - val_accuracy: 0.7980
Epoch 4/200
235/235 [==============================] - 1s 3ms/step - loss: 0.5044 - accuracy: 0.7957 - val_loss: 0.4986 - val_accuracy: 0.7980
Epoch 5/200
235/235 [==============================] - 1s 2ms/step - loss: 0.4941 - accuracy: 0.7957 - val_loss: 0.4902 - val_accuracy: 0.7980
Epoch 6/200
235/235 [==============================] - 0s 2ms/step - loss: 0.4859 - accuracy: 0.7957 - val_loss: 0.4828 - val_accuracy: 0.7980
Epoch 7/200
235/235 [==============================] - 1s 2ms/step - loss: 0.4777 - accuracy: 0.7957 - val_loss: 0.4744 - val_accuracy: 0.7980

In [ ]:
y_pred1=model.predict(x_test)
y_pred1

79/79 [==============================] - 0s 2ms/step


array([[0.9325512 , 0.06744917],
       [0.9803596 , 0.01964057],
       [0.7794133 , 0.2205873 ],
       ...,
       [0.95330685, 0.04669331],
       [0.89955187, 0.10044796],
       [0.8442282 , 0.15577145]], dtype=float32)

In [ ]:
y_test_class=np.argmax(y_test,axis=1)
y_pred1_class=np.argmax(y_pred1,axis=1)
y_pred1_class,y_test_class

(array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]))

Model Evaluation

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [ ]:
print(confusion_matrix(y_test_class,y_pred1_class))
print(classification_report(y_test_class,y_pred1_class))
print(accuracy_score(y_test_class,y_pred1_class))

[[1980   15]
 [ 434   71]]
              precision    recall  f1-score   support

           0       0.82      0.99      0.90      1995
           1       0.83      0.14      0.24       505

    accuracy                           0.82      2500
   macro avg       0.82      0.57      0.57      2500
weighted avg       0.82      0.82      0.77      2500

0.8204
