## Data Acquisition

## 2. Text Preperation

2.1. Text Cleanup

In [ ]:
#2.1.a. HTML Tags
text = '<h2> HTML Element</h2><p> <The Class"w3> ,glt;supsgt'

In [ ]:
#remove html tags
import re
def html(data):
  p = re.compile('(<.*?>)')
  return p.sub('',data)

In [ ]:
html(text)

' HTML Element  ,glt;supsgt'

In [ ]:
#2.1.b. Emoji
emoji = '😃💁‍♂People • 🐻🌻Animals •🍔🍹Food •🎷⚽Activities •🚘🌇Travel •🛏🛋Objects •❌❓Symbols •🚩🏳‍🌈Flags•'
emoji.encode('utf-8')
# to convert in machine understandable text

b'\xf0\x9f\x98\x83\xf0\x9f\x92\x81\xe2\x80\x8d\xe2\x99\x82People \xe2\x80\xa2 \xf0\x9f\x90\xbb\xf0\x9f\x8c\xbbAnimals \xe2\x80\xa2\xf0\x9f\x8d\x94\xf0\x9f\x8d\xb9Food \xe2\x80\xa2\xf0\x9f\x8e\xb7\xe2\x9a\xbdActivities \xe2\x80\xa2\xf0\x9f\x9a\x98\xf0\x9f\x8c\x87Travel \xe2\x80\xa2\xf0\x9f\x9b\x8f\xf0\x9f\x9b\x8bObjects \xe2\x80\xa2\xe2\x9d\x8c\xe2\x9d\x93Symbols \xe2\x80\xa2\xf0\x9f\x9a\xa9\xf0\x9f\x8f\xb3\xe2\x80\x8d\xf0\x9f\x8c\x88Flags\xe2\x80\xa2'

In [ ]:
!pip install textblob

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
#2.1.c. spelling check
spelling_mistakes = 'hello, how aree you, what aree you doing these days'

In [ ]:
from textblob import TextBlob

In [ ]:
correct_spelling = TextBlob(spelling_mistakes)

In [ ]:
correct_spelling

TextBlob("hello, how aree you, what aree you doing these days")

In [ ]:
correct_spelling.correct()

TextBlob("hello, how are you, what are you doing these days")

2.2. Basic Preprocessing

In [ ]:
data = '''Text-based emoticons are great because they work on most devices and browsers. Whether you're commenting on a post or texting with a friend,they are handy if you're perfect response isn't a word but an emotion.'''

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
from nltk.tokenize import sent_tokenize, word_tokenize
sents = sent_tokenize(data)

In [ ]:
sents

['Text-based emoticons are great because they work on most devices and browsers.',
 "Whether you're commenting on a post or texting with a friend,they are handy if you're perfect response isn't a word but an emotion."]

In [ ]:
word = word_tokenize(data)
word

['Text-based',
 'emoticons',
 'are',
 'great',
 'because',
 'they',
 'work',
 'on',
 'most',
 'devices',
 'and',
 'browsers',
 '.',
 'Whether',
 'you',
 "'re",
 'commenting',
 'on',
 'a',
 'post',
 'or',
 'texting',
 'with',
 'a',
 'friend',
 ',',
 'they',
 'are',
 'handy',
 'if',
 'you',
 "'re",
 'perfect',
 'response',
 'is',
 "n't",
 'a',
 'word',
 'but',
 'an',
 'emotion',
 '.']

2.3. Optimal/ Optional

In [ ]:
#2.3.1. Stop words remover
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
from nltk.corpus import stopwords
stopwords = set(stopwords.words('english'))

In [ ]:
words = []
for w in word:
  if w not in stopwords:
    print(w)
    words.append(w)

Text-based
emoticons
great
work
devices
browsers
.
Whether
're
commenting
post
texting
friend
,
handy
're
perfect
response
n't
word
emotion
.


In [ ]:
words

['Text-based',
 'emoticons',
 'great',
 'work',
 'devices',
 'browsers',
 '.',
 'Whether',
 "'re",
 'commenting',
 'post',
 'texting',
 'friend',
 ',',
 'handy',
 "'re",
 'perfect',
 'response',
 "n't",
 'word',
 'emotion',
 '.']

In [ ]:
#2.3.2. Stemming or Lamentization

In [ ]:
from nltk.stem import PorterStemmer
#create an object of class PorterStemmer
porter = PorterStemmer()
print(porter.stem("play"))
print(porter.stem("playing"))
print(porter.stem("plays"))
print(porter.stem("played"))

play
play
play
play


In [ ]:
from nltk.stem import PorterStemmer
#create an object of class PorterStemmer
porter = PorterStemmer()
print(porter.stem("Communication"))

commun


In [ ]:
import nltk
from nltk.stem.porter import *
p_stemmer = PorterStemmer()
for word in words:
  print(word+'-->'+p_stemmer.stem(word))

Text-based-->text-bas
emoticons-->emoticon
great-->great
work-->work
devices-->devic
browsers-->browser
.-->.
Whether-->whether
're-->'re
commenting-->comment
post-->post
texting-->text
friend-->friend
,-->,
handy-->handi
're-->'re
perfect-->perfect
response-->respons
n't-->n't
word-->word
emotion-->emot
.-->.


In [ ]:
import nltk
from nltk.stem.porter import *
p_stemmer = PorterStemmer()
for word in words:
  print(p_stemmer.stem(word))

text-bas
emoticon
great
work
devic
browser
.
whether
're
comment
post
text
friend
,
handi
're
perfect
respons
n't
word
emot
.


In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
import nltk
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
for word in words:
  print(word+' --> '+lemmatizer.lemmatize(word))

Text-based --> Text-based
emoticons --> emoticon
great --> great
work --> work
devices --> device
browsers --> browser
. --> .
Whether --> Whether
're --> 're
commenting --> commenting
post --> post
texting --> texting
friend --> friend
, --> ,
handy --> handy
're --> 're
perfect --> perfect
response --> response
n't --> n't
word --> word
emotion --> emotion
. --> .


In [ ]:
import nltk
words_1 = []
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
for word in words:
  print(lemmatizer.lemmatize(word))
  words_1.append(word)

Text-based
emoticon
great
work
device
browser
.
Whether
're
commenting
post
texting
friend
,
handy
're
perfect
response
n't
word
emotion
.


In [ ]:
words_1

['Text-based',
 'emoticons',
 'great',
 'work',
 'devices',
 'browsers',
 '.',
 'Whether',
 "'re",
 'commenting',
 'post',
 'texting',
 'friend',
 ',',
 'handy',
 "'re",
 'perfect',
 'response',
 "n't",
 'word',
 'emotion',
 '.']

In [ ]:
#2.3.3. Removing digits and punctuations

In [ ]:
#defining punctuation
punctuations = '''!()-{};:'"\,<>./?@#$%^&*_~'''

#removing punctuations from the string
no_punct =""
for char in words_1:
  if char not in punctuations:
    no_punct = no_punct + char

#display the unpunctuated string
print(no_punct)

Text-basedemoticonsgreatworkdevicesbrowsersWhether'recommentingposttextingfriendhandy'reperfectresponsen'twordemotion


In [ ]:
digit_1_10 = '''Text-basedemoticon1111sgreatworkdevices23brow45sersWhether'recommenti989ngposttextingfrie652ndhandy'reperfectres011ponsen'twordemotion'''

digits = '''0-1'''
#remove punctuation from the string
no_digits = ""
for char in words_1:
  if char not in digits:
    no_digits = no_digits + char

#display the unpunctuated string
print(no_digits)

Text-basedemoticonsgreatworkdevicesbrowsers.Whether'recommentingposttextingfriend,handy'reperfectresponsen'twordemotion.


lowercase

In [ ]:
def wordlowercase():
  text = 'An Easy Way To Change UpperCase To LowerCase And Title Capitalization'
  return text.lower()

In [ ]:
wordlowercase()

'an easy way to change uppercase to lowercase and title capitalization'

## 2.3. Advance Preprocessing

## NLP Classification

In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv('/content/twitter_dataset_nlp.csv')
df.head()

Unnamed: 0                                               text label
0           0  @Pericles216 @HierBeforeTheAC @Sachinettiyil T...  intj
1           1  @Hispanthicckk Being you makes you look cute||...  intj
2           2  @Alshymi Les balles sont réelles et sont tirée...  intj
3           3  I'm like entp but idiotic|||Hey boy, do you wa...  intj
4           4  @kaeshurr1 Give it to @ZargarShanif ... He has...  intj

In [ ]:
y = df['label']

In [ ]:
df['label'].value_counts(),df['label'].nunique()

(infp    1282
 infj    1057
 intp     811
 intj     781
 enfp     729
 entp     577
 enfj     518
 isfp     367
 isfj     364
 istp     327
 entj     279
 istj     259
 esfp     174
 esfj     105
 estp     100
 estj      81
 Name: label, dtype: int64,
 16)

In [ ]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
y = lb.fit_transform(y)
y

array([10, 10, 10, ...,  3,  8, 15])

In [ ]:
df.shape

(7811, 3)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7811 entries, 0 to 7810
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  7811 non-null   int64 
 1   text        7811 non-null   object
 2   label       7811 non-null   object
dtypes: int64(1), object(2)
memory usage: 183.2+ KB


In [ ]:
#lowercase for 4th row
df['text'][4].lower()

"@kaeshurr1 give it to @zargarshanif ... he has pica since childhood|||@dannnyaaaa say qubool hai in my dm ❤️|||@dannnyaaaa get married asap|||@ubaid_rasool two decades actually 🌚|||@kaeshurr1 @umer__ayoub subas ?|||@kaeshurr1 @umer__ayoub wayne kar niyiv meati panas seyt|||@kaeshurr1 @umer__ayoub mea gov akh hafte czeaf dith|||@kaeshurr1 @umer__ayoub meati niyziha panas seyt|||okay 🥺 https://t.co/3fh1tqbfl2|||@hareembhat_ https://t.co/0nve1cdbqd|||@pingaapongaa hye|||@bint_e_tasleem i had a lot to speak out, but you ignored me 🥺|||@whytaniya welcome back|||just a simple thought, what's stopping from having icu facilities at dh shopian? 50-70% deaths occur due to referra… https://t.co/wpcgmdzsar|||@toyibanabi laxmi chit fund bank|||same bro same 🥺🌚 https://t.co/2g5zorfhsf|||@yawar_banday expecting a grand opening soon in sha allah???|||@dannnyaaaa aameeeeeeeennnn|||@babra_yousuf mohabat|||@yawar_banday thanks for bringing the coolest place ever seen ❤️|||@aadilsam118 mujhe b le jao tan

In [ ]:
text = df['text']

In [ ]:
#convert in lowercase
text = text.str.lower()

In [ ]:
#remove html tags
import re
def remove_html_tags(text):
  pattern = re.compile('<.*?>')
  return pattern.sub(r'',text)


In [ ]:
text = text.apply(remove_html_tags)
text


0       @pericles216 @hierbeforetheac @sachinettiyil t...
1       @hispanthicckk being you makes you look cute||...
2       @alshymi les balles sont réelles et sont tirée...
3       i'm like entp but idiotic|||hey boy, do you wa...
4       @kaeshurr1 give it to @zargarshanif ... he has...
                              ...                        
7806    @sobsjjun god,,pls take care 😕|||@sobsjjun hir...
7807    @ignis_02 wow last time i got intp https://t.c...
7808    @akupilled a 100%|||@akupilled that someone wi...
7809    if you’re #intj this one is for you | what is ...
7810    @harry__lambert @gucci hey can you dm me a pic...
Name: text, Length: 7811, dtype: object

In [ ]:
#clear url
def remove_url(text):
  pattern = re.compile(r'https?://\S+|www\.\s+')
  return pattern.sub(r'', text)

In [ ]:
text = text.apply(remove_url)
text

0       @pericles216 @hierbeforetheac @sachinettiyil t...
1       @hispanthicckk being you makes you look cute||...
2       @alshymi les balles sont réelles et sont tirée...
3       i'm like entp but idiotic|||hey boy, do you wa...
4       @kaeshurr1 give it to @zargarshanif ... he has...
                              ...                        
7806    @sobsjjun god,,pls take care 😕|||@sobsjjun hir...
7807    @ignis_02 wow last time i got intp    i think ...
7808    @akupilled a 100%|||@akupilled that someone wi...
7809    if you’re #intj this one is for you | what is ...
7810    @harry__lambert @gucci hey can you dm me a pic...
Name: text, Length: 7811, dtype: object

In [ ]:
#remove punctuations - method 1

import string,time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
exclude = string.punctuation

In [ ]:
def remove_punctuation(text):
  for char in exclude:
    text = text.replace(char,'')
  return text

In [ ]:
start = time.time()
print(remove_punctuation(text))
time1 = time.time() - start
print(time1)

0       @pericles216 @hierbeforetheac @sachinettiyil t...
1       @hispanthicckk being you makes you look cute||...
2       @alshymi les balles sont réelles et sont tirée...
3       i'm like entp but idiotic|||hey boy, do you wa...
4       @kaeshurr1 give it to @zargarshanif ... he has...
                              ...                        
7806    @sobsjjun god,,pls take care 😕|||@sobsjjun hir...
7807    @ignis_02 wow last time i got intp    i think ...
7808    @akupilled a 100%|||@akupilled that someone wi...
7809    if you’re #intj this one is for you | what is ...
7810    @harry__lambert @gucci hey can you dm me a pic...
Name: text, Length: 7811, dtype: object
0.041059255599975586


In [ ]:
#remove punctuation - method 2
def remove_punc1(text):
  return text.translate(str.maketrans('','',exclude))

In [ ]:
text = text.apply(remove_punc1)

In [ ]:
start = time.time()
text = text.apply(remove_punc1)
time2 = time.time() - start
print(time2)

5.646285772323608


In [ ]:
time1/time2

0.007271905329559422

In [ ]:
#remove punctuations - method 3
punc = '''!()-[]{};:'"\,<>./?|@#$%^&*_~'''

def remove_punc(text):
  for char in punc:
    text = text.replace(char,'')
  return text

In [ ]:
text = text.apply(remove_punc)
text

0       pericles216 hierbeforetheac sachinettiyil the ...
1       hispanthicckk being you makes you look cutethi...
2       alshymi les balles sont réelles et sont tirées...
3       im like entp but idiotichey boy do you want to...
4       kaeshurr1 give it to zargarshanif  he has pica...
                              ...                        
7806    sobsjjun godpls take care 😕sobsjjun hiro emerg...
7807    ignis02 wow last time i got intp    i think u ...
7808    akupilled a 100akupilled that someone will get...
7809    if you’re intj this one is for you  what is ne...
7810    harrylambert gucci hey can you dm me a pic of ...
Name: text, Length: 7811, dtype: object

In [ ]:
import time
start = time.time()
remove_punc(text)
time3 = time.time() - start
print(time3)

0.04179644584655762


In [ ]:
time3/time2

0.007402467308939835

In [ ]:
text[7806]

'sobsjjun godpls take care 😕sobsjjun hiro emergency room are you okay waitdafahoe zeharrrrrrr😭😭😭😭😭😭😭😭txtlomlsss ye0nyang oh my god thats 💔ye0nyang txtlomlsss did i liesoobinspolaroid i knownano h—\nsoule  grandma   r so cute😭my whole tl just 4 oomfs doing sum shit but i love itsoobinspolaroid is this u0x1bts plus i took a test yesterday and i am an intp ur so annoying0x1bts dude atleast speak in english what if he minds wtfsoobinspolaroid sobsjjun oh my godsoobinspolaroid sobsjjun who tf tells before stealing just steal when hes sleeping or sum shit 😭0x1bts soobinspolaroid what the fuck0x1bts soobinspolaroid  im intpi should stop making jokes  helpbeomthyusiast1 nooooo😭ye0nyang snakskdmkwkwmdmbeomthyusiast1 who said im jokingyeehawnjun im so funnytxtlomlsss rightt im so geniusox1gyuu sooo truecactigumi im so funnytxtlomlsss im geniuschoiseeker yesyuniberri yunnie twtstolen btwif a shark bites ubite back  youll still d1e but the shark would be like yo wtfinsoobinspolaroid i love kids to

## Handle Emoji

In [ ]:
!pip install emoji

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 240.9/240.9 kB 5.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for emoji: filename=emoji-2.2.0-py3-none-any.whl size=234926 sha256=37a2732f9bdee6b3c8e8654e785863550e7f7b8033a73864d710408471f7f5a9
  Stored in directory: /root/.cache/pip/wheels/9a/b8/0f/f580817231cbf59f6ade9fd132ff60ada1de9f7dc85521f857
Successfully built emoji


In [ ]:
!pip install emoji --upgrade

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import emoji
print(emoji.demojize(text[7606]))

guys omg  so happy they got to meet again  sayangku :loudly_crying_face::loudly_crying_face::loudly_crying_face::loudly_crying_face:wetheboyz sayangi hope their arms is the last thing i see before i sleep and then i will be dreaming about sanghak arms toogoing crazy  one chance please give me one chance :face_with_hand_over_mouth::grinning_face_with_smiling_eyes::rolling_on_the_floor_laughing::beaming_face_with_smiling_eyes::face_holding_back_tears::grinning_squinting_face:guys i love haknyeon so muchsanghaakkkkkkkkkkkkk armsssssssssss:grinning_face_with_smiling_eyes::grinning_face_with_smiling_eyes::grinning_face_with_smiling_eyes::grinning_face_with_smiling_eyes::grinning_face_with_smiling_eyes::grinning_face_with_smiling_eyes::grinning_face_with_smiling_eyes:  ilywetheboyz omgwetheboyz juyeonliterally what the fucklord  shut up  hak ily:grinning_face_with_smiling_eyes::grinning_face_with_smiling_eyes:  i love youwetheboyz omgoh my bbangnyuman…   am i suppose to move on what   baby  

In [ ]:
text[7606].encode('utf-8')

b'guys omg  so happy they got to meet again  sayangku \xf0\x9f\x98\xad\xf0\x9f\x98\xad\xf0\x9f\x98\xad\xf0\x9f\x98\xadwetheboyz sayangi hope their arms is the last thing i see before i sleep and then i will be dreaming about sanghak arms toogoing crazy  one chance please give me one chance \xf0\x9f\xa4\xad\xf0\x9f\x98\x84\xf0\x9f\xa4\xa3\xf0\x9f\x98\x81\xf0\x9f\xa5\xb9\xf0\x9f\x98\x86guys i love haknyeon so muchsanghaakkkkkkkkkkkkk armsssssssssss\xf0\x9f\x98\x84\xf0\x9f\x98\x84\xf0\x9f\x98\x84\xf0\x9f\x98\x84\xf0\x9f\x98\x84\xf0\x9f\x98\x84\xf0\x9f\x98\x84  ilywetheboyz omgwetheboyz juyeonliterally what the fucklord  shut up  hak ily\xf0\x9f\x98\x84\xf0\x9f\x98\x84  i love youwetheboyz omgoh my bbangnyuman\xe2\x80\xa6   am i suppose to move on what   baby  i love you so muchcravitystarship thank you youngtae \xf0\x9f\xab\xb6\xf0\x9f\xab\xb6\xf0\x9f\xab\xb6hey god its me again  my loveswetheboyz thank youwetheboyz oh my godbbangnyuanother win for me today as a fengfan and juyeon enthusi

In [ ]:
type(text)

pandas.core.series.Series

In [ ]:
test = [[text]]

In [ ]:
text

0       pericles216 hierbeforetheac sachinettiyil the ...
1       hispanthicckk being you makes you look cutethi...
2       alshymi les balles sont réelles et sont tirées...
3       im like entp but idiotichey boy do you want to...
4       kaeshurr1 give it to zargarshanif  he has pica...
                              ...                        
7806    sobsjjun godpls take care 😕sobsjjun hiro emerg...
7807    ignis02 wow last time i got intp    i think u ...
7808    akupilled a 100akupilled that someone will get...
7809    if you’re intj this one is for you  what is ne...
7810    harrylambert gucci hey can you dm me a pic of ...
Name: text, Length: 7811, dtype: object

In [ ]:
text = pd.DataFrame(text)
text

text
0     pericles216 hierbeforetheac sachinettiyil the ...
1     hispanthicckk being you makes you look cutethi...
2     alshymi les balles sont réelles et sont tirées...
3     im like entp but idiotichey boy do you want to...
4     kaeshurr1 give it to zargarshanif  he has pica...
...                                                 ...
7806  sobsjjun godpls take care 😕sobsjjun hiro emerg...
7807  ignis02 wow last time i got intp    i think u ...
7808  akupilled a 100akupilled that someone will get...
7809  if you’re intj this one is for you  what is ne...
7810  harrylambert gucci hey can you dm me a pic of ...

[7811 rows x 1 columns]

In [ ]:
type(text)

pandas.core.frame.DataFrame

In [ ]:
import emoji
text = text.astype(str).apply(lambda x: x.str.encode('ascii', 'ignore').str.decode('latin-1'))

In [ ]:
text.shape

(7811, 1)

In [ ]:
text[7606:7607]

text
7606  guys omg  so happy they got to meet again  say...

In [ ]:
text = text['text']

In [ ]:
text.shape

(7811,)

In [ ]:
type(text)

pandas.core.series.Series

In [ ]:
text

0       pericles216 hierbeforetheac sachinettiyil the ...
1       hispanthicckk being you makes you look cutethi...
2       alshymi les balles sont relles et sont tires t...
3       im like entp but idiotichey boy do you want to...
4       kaeshurr1 give it to zargarshanif  he has pica...
                              ...                        
7806    sobsjjun godpls take care sobsjjun hiro emerge...
7807    ignis02 wow last time i got intp    i think u ...
7808    akupilled a 100akupilled that someone will get...
7809    if youre intj this one is for you  what is nev...
7810    harrylambert gucci hey can you dm me a pic of ...
Name: text, Length: 7811, dtype: object

In [ ]:
df['text']

0       @Pericles216 @HierBeforeTheAC @Sachinettiyil T...
1       @Hispanthicckk Being you makes you look cute||...
2       @Alshymi Les balles sont réelles et sont tirée...
3       I'm like entp but idiotic|||Hey boy, do you wa...
4       @kaeshurr1 Give it to @ZargarShanif ... He has...
                              ...                        
7806    @sobsjjun God,,pls take care 😕|||@sobsjjun Hir...
7807    @Ignis_02 wow last time i got intp https://t.c...
7808    @akupilled A 100%|||@akupilled That SOMEONE wi...
7809    If you’re #INTJ this one is for you | What is ...
7810    @harry__lambert @gucci hey can you dm me a pic...
Name: text, Length: 7811, dtype: object

## Tokenization

In [ ]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [ ]:
text = pd.DataFrame(text)
text

text
0     pericles216 hierbeforetheac sachinettiyil the ...
1     hispanthicckk being you makes you look cutethi...
2     alshymi les balles sont relles et sont tires t...
3     im like entp but idiotichey boy do you want to...
4     kaeshurr1 give it to zargarshanif  he has pica...
...                                                 ...
7806  sobsjjun godpls take care sobsjjun hiro emerge...
7807  ignis02 wow last time i got intp    i think u ...
7808  akupilled a 100akupilled that someone will get...
7809  if youre intj this one is for you  what is nev...
7810  harrylambert gucci hey can you dm me a pic of ...

[7811 rows x 1 columns]

In [ ]:
text['text']

0       pericles216 hierbeforetheac sachinettiyil the ...
1       hispanthicckk being you makes you look cutethi...
2       alshymi les balles sont relles et sont tires t...
3       im like entp but idiotichey boy do you want to...
4       kaeshurr1 give it to zargarshanif  he has pica...
                              ...                        
7806    sobsjjun godpls take care sobsjjun hiro emerge...
7807    ignis02 wow last time i got intp    i think u ...
7808    akupilled a 100akupilled that someone will get...
7809    if youre intj this one is for you  what is nev...
7810    harrylambert gucci hey can you dm me a pic of ...
Name: text, Length: 7811, dtype: object

In [ ]:
sent_tokenize

<function nltk.tokenize.sent_tokenize(text, language='english')>

In [ ]:
text['text']

0       pericles216 hierbeforetheac sachinettiyil the ...
1       hispanthicckk being you makes you look cutethi...
2       alshymi les balles sont relles et sont tires t...
3       im like entp but idiotichey boy do you want to...
4       kaeshurr1 give it to zargarshanif  he has pica...
                              ...                        
7806    sobsjjun godpls take care sobsjjun hiro emerge...
7807    ignis02 wow last time i got intp    i think u ...
7808    akupilled a 100akupilled that someone will get...
7809    if youre intj this one is for you  what is nev...
7810    harrylambert gucci hey can you dm me a pic of ...
Name: text, Length: 7811, dtype: object

In [ ]:
word_tokenize = text['text'].apply(word_tokenize)

In [ ]:
word_tokenize

0       [pericles216, hierbeforetheac, sachinettiyil, ...
1       [hispanthicckk, being, you, makes, you, look, ...
2       [alshymi, les, balles, sont, relles, et, sont,...
3       [im, like, entp, but, idiotichey, boy, do, you...
4       [kaeshurr1, give, it, to, zargarshanif, he, ha...
                              ...                        
7806    [sobsjjun, godpls, take, care, sobsjjun, hiro,...
7807    [ignis02, wow, last, time, i, got, intp, i, th...
7808    [akupilled, a, 100akupilled, that, someone, wi...
7809    [if, youre, intj, this, one, is, for, you, wha...
7810    [harrylambert, gucci, hey, can, you, dm, me, a...
Name: text, Length: 7811, dtype: object

In [ ]:
text1 = pd.DataFrame(word_tokenize)
text['text']

0       pericles216 hierbeforetheac sachinettiyil the ...
1       hispanthicckk being you makes you look cutethi...
2       alshymi les balles sont relles et sont tires t...
3       im like entp but idiotichey boy do you want to...
4       kaeshurr1 give it to zargarshanif  he has pica...
                              ...                        
7806    sobsjjun godpls take care sobsjjun hiro emerge...
7807    ignis02 wow last time i got intp    i think u ...
7808    akupilled a 100akupilled that someone will get...
7809    if youre intj this one is for you  what is nev...
7810    harrylambert gucci hey can you dm me a pic of ...
Name: text, Length: 7811, dtype: object

## Stop Words

In [ ]:
from nltk.corpus import stopwords

In [ ]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
def remove_stopwords(text):
  for char in stopwords.words('english'):
    text = text.replace(char,'')
  return text

text.apply(remove_stopwords)

text
0     pericles216 hierbeforetheac sachinettiyil the ...
1     hispanthicckk being you makes you look cutethi...
2     alshymi les balles sont relles et sont tires t...
3     im like entp but idiotichey boy do you want to...
4     kaeshurr1 give it to zargarshanif  he has pica...
...                                                 ...
7806  sobsjjun godpls take care sobsjjun hiro emerge...
7807  ignis02 wow last time i got intp    i think u ...
7808  akupilled a 100akupilled that someone will get...
7809  if youre intj this one is for you  what is nev...
7810  harrylambert gucci hey can you dm me a pic of ...

[7811 rows x 1 columns]

In [ ]:
text

text
0     pericles216 hierbeforetheac sachinettiyil the ...
1     hispanthicckk being you makes you look cutethi...
2     alshymi les balles sont relles et sont tires t...
3     im like entp but idiotichey boy do you want to...
4     kaeshurr1 give it to zargarshanif  he has pica...
...                                                 ...
7806  sobsjjun godpls take care sobsjjun hiro emerge...
7807  ignis02 wow last time i got intp    i think u ...
7808  akupilled a 100akupilled that someone will get...
7809  if youre intj this one is for you  what is nev...
7810  harrylambert gucci hey can you dm me a pic of ...

[7811 rows x 1 columns]

## Feature Engineering

Count Vectorizer

In [ ]:
text[7809:7810]

text
7809  if youre intj this one is for you  what is nev...

In [ ]:
#count vectorizer
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x1 = cv.fit_transform(text[7809:7810])
x1.shape

(1, 1)

In [ ]:
x1

<1x1 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [ ]:
text[['text']]

text
0     pericles216 hierbeforetheac sachinettiyil the ...
1     hispanthicckk being you makes you look cutethi...
2     alshymi les balles sont relles et sont tires t...
3     im like entp but idiotichey boy do you want to...
4     kaeshurr1 give it to zargarshanif  he has pica...
...                                                 ...
7806  sobsjjun godpls take care sobsjjun hiro emerge...
7807  ignis02 wow last time i got intp    i think u ...
7808  akupilled a 100akupilled that someone will get...
7809  if youre intj this one is for you  what is nev...
7810  harrylambert gucci hey can you dm me a pic of ...

[7811 rows x 1 columns]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x1 = cv.fit_transform(text['text'])
x1.shape

(7811, 736582)

In [ ]:
x1

<7811x736582 sparse matrix of type '<class 'numpy.int64'>'
	with 4425658 stored elements in Compressed Sparse Row format>

## TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer


In [ ]:
tr_idf_model = TfidfVectorizer()
tf_idf = tr_idf_model.fit_transform(text['text'])

In [ ]:
tf_idf.size

4425658

In [ ]:
print(type(tf_idf), tf_idf.shape)

<class 'scipy.sparse._csr.csr_matrix'> (7811, 736582)


In [ ]:
from keras.utils import np_utils
npy = np_utils.to_categorical(y)
print(npy[:5])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x1,npy,test_size=.25,random_state=1)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(5858, 736582)
(1953, 736582)
(5858, 16)
(1953, 16)


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler(with_mean=False)
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(5858, 736582)
(1953, 736582)
(5858, 16)
(1953, 16)


In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense,Activation,Dropout
from keras.optimizers import adam
from keras.metrics import categorical_crossentropy

In [ ]:
model = Sequential()
model.add(Dense(units=160,activation='relu',input_dim=736582))
model.add(Dropout(0.1))
model.add(Dense(units=16,activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(units=16,activation='sigmoid'))

In [ ]:
model.compile(optimizer= 'Adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 160)               117853280 
                                                                 
 dropout (Dropout)           (None, 160)               0         
                                                                 
 dense_1 (Dense)             (None, 16)                2576      
                                                                 
 dropout_1 (Dropout)         (None, 16)                0         
                                                                 
 dense_2 (Dense)             (None, 16)                272       
                                                                 
Total params: 117,856,128
Trainable params: 117,856,128
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(x_train,y_train,epochs=1,verbose=1)

184/184 [==============================] - 469s 3s/step - loss: 2.8088 - accuracy: 0.1571


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/twitter_dataset_nlp.csv')
df.head()
y = df['label']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import RegexpTokenizer
token = RegexpTokenizer(r'[a-zA-Z0-9]+')
cv = CountVectorizer(lowercase = True,stop_words='english',ngram_range=(1,1), tokenizer = None)
x = cv.fit_transform(text['text'])
x

<7811x736274 sparse matrix of type '<class 'numpy.int64'>'
	with 3612805 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
x = tf.fit_transform(text['text'])
x

<7811x736582 sparse matrix of type '<class 'numpy.float64'>'
	with 4425658 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
y = lb.fit_transform(df['label'])
y

array([10, 10, 10, ...,  3,  8, 15])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.25)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(5858, 736582)
(1953, 736582)
(5858,)
(1953,)


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler(with_mean=False)
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
nb = MultinomialNB().fit(x_train,y_train)
nb

MultinomialNB()

In [ ]:
nb.score(x_train,y_train)

0.999829293274155

In [ ]:
y_pred_nb = nb.predict(x_test)
print(len(y_pred_nb))
y_pred_nb

1953


array([ 8,  3,  8, ...,  8, 10, 10])

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [ ]:
metrics.accuracy_score(y_test,y_pred_nb)

0.20686123911930362

In [ ]:
print(confusion_matrix(y_test,y_pred_nb))

[[26  4  2  8  2  2  5  7 18 17 20  4  3  2  1  3]
 [ 7 22  3 14  2  4  5  2 23 38 23 10  9  4  3  3]
 [ 4  3  1  4  3  3  2  0 11  6 14  3  1  1  2  0]
 [ 3 11  3 17  2  1  8  3 15 20 22  6  2  5 13  2]
 [ 2  2  0  2  2  0  1  2  4  4  3  3  2  1  0  1]
 [ 2  1  0  1  0 10  1  1  2  7  2  3  2  0  0  2]
 [ 2  2  1  1  0  0  6  1  4  3  7  1  0  0  0  0]
 [ 1  2  1  3  0  0  2  3  2  0  1  3  0  2  0  1]
 [11 18 13  6  3  6  6  3 87 30 51 10 10  3  9  3]
 [15 24 11 13 10  5 16  7 40 96 43 21 13 14  9  8]
 [ 4 15  6  2  2  2 10  1 33 31 47  7  7  6  6  3]
 [ 9 12  8 10  2  5 12  4 37 30 34 36  7  5  3  6]
 [ 7  3  2  2  6  2  6  2 15 21  9  6 14  4  3  3]
 [ 8  4  1  5  2  2  3  1  8 14  4 11  3 13  2  4]
 [ 4  3  4  3  1  2  5  1  4  6 16  6  4  2  8  2]
 [ 0  5  1  4  0  2  4  1  7 12  7  7  4  5  2 16]]
